#!/usr/bin/env python3
"""Compile the editable verb catalogue into the shared model. Use --check in CI."""
import json, pathlib, sys
root=pathlib.Path(__file__).resolve().parents[1]
rows=json.loads((root/'content/verbs/catalogue.json').read_text())
quote=lambda s: json.dumps(s,ensure_ascii=False)
lines=['// Generated by scripts/build_verb_tables.py from content/verbs/catalogue.json.', '// Edit the source catalogue and regenerate; do not edit this table.', 'enum VerbTables {', '    static let all: [TrainingVerb] = [']
for r in rows:
 assert all(len(v)==6 for v in r['forms'].values()),r['id']
 values=', '.join(f'{k}: {quote(r[k])}' for k in ['id','english','third','past','englishParticiple','tail','englishTail','participle','gerund'])
 lines.append('        .init('+values+', reflexive: '+str(r.get('reflexive',False)).lower()+', forms: [')
 for key,forms in r['forms'].items(): lines.append('            .'+key+': ['+', '.join(map(quote,forms))+'],')
 lines.append('        ]),')
lines += ['    ]','}','']
out=root/'Cuentiva/2 - AppModel/Features/Verbs/VerbTables.swift';text='\n'.join(lines)
if '--check' in sys.argv:
 if out.read_text()!=text: raise SystemExit('Verb tables are stale; run scripts/build_verb_tables.py')
else:out.write_text(text)
print(f'{len(rows)} verbs; {len(rows)*9*6} explicit simple-form slots (command yo intentionally empty).')
