import Foundation

/// Editorially seeded demo priorities, not measured community demand or publication data.
struct LocalTopicRequestRepository: TopicRequestRepository {
    func requests() async throws -> [TopicRequest] {
        let teaching = ["I explain the meaning in my own words.", "I show why a learner would use it in this situation.", "I explain my examples so a new reader can follow them."]
        return [
            .init(id: "haber-introductions", title: "Haber · meeting for the first time", category: "Verbs", priority: "Top priority", brief: "Help two people meeting for the first time talk about experiences: ‘He venido con Ana’ or ‘¿Has conocido a Luis?’. Explain how haber helps another verb describe what has happened. Build a short, memorable story, then teach the reader why those words matter.", scope: "Present indicative as an auxiliary: he, has, ha, hemos, habéis, han, each followed by a participle in your examples. Use each form in two meaningful sentences. Habéis is the vosotros form used in Spain; usted/ustedes use ha/han. This ticket does not cover every tense. Explain hay separately as ‘there is/there are’; it does not change for plural things. Haber is not the usual verb for possessing something (tener).", forms: ["he", "has", "ha", "hemos", "habéis", "han"], requirements: teaching + ["My story involves people meeting for the first time.", "I distinguish auxiliary haber from hay and tener."], target: 3, reviewedBooks: 0, demoExamples: 0),
            .init(id: "tener-first-day", title: "Tener · a difficult first day", category: "Verbs", priority: "High priority", brief: "Tell a first-day story in which people describe what they have and what they need. Help future readers understand expressions such as tener miedo and tener hambre through the characters’ experience.", scope: "Present indicative, including vosotros (Spain). Use every listed form twice in meaningful Spanish sentences; explain examples rather than listing conjugations.", forms: ["tengo", "tienes", "tiene", "tenemos", "tenéis", "tienen"], requirements: teaching, target: 3, reviewedBooks: 0, demoExamples: 0),
            .init(id: "ir-new-city", title: "Ir · finding each other", category: "Verbs", priority: "High priority", brief: "Two friends are lost in a new city. Show where each person is going and why ir helps them make plans and find one another.", scope: "Present indicative, including vosotros (Spain). Use each listed form twice. Explain the destination in each example.", forms: ["voy", "vas", "va", "vamos", "vais", "van"], requirements: teaching, target: 3, reviewedBooks: 0, demoExamples: 0),
            .init(id: "ser-identities", title: "Ser · introducing who we are", category: "Verbs", priority: "Build coverage", brief: "We have one demo story about ser. Add a different situation: people introducing their relationships, work, or origins. Explain the identity each example communicates.", scope: "Present indicative, including vosotros (Spain). Use each form twice. Avoid teaching ser as simply ‘permanent’: that shortcut does not explain all its uses.", forms: ["soy", "eres", "es", "somos", "sois", "son"], requirements: teaching, target: 3, reviewedBooks: 0, demoExamples: 1),
            .init(id: "asking-directions", title: "Asking for directions kindly", category: "Everyday life", priority: "High priority", brief: "Write a story in which a visitor asks for directions, checks what they heard, and thanks the person helping. Explain why the phrases make the conversation easier.", scope: "A1–A2 audience. Keep directions understandable and show clarification when someone is confused. This request has no required conjugation set.", forms: [], requirements: teaching + ["My character asks for clarification and thanks the helper."], target: 2, reviewedBooks: 0, demoExamples: 0),
            .init(id: "kind-disagreement", title: "Disagreeing without losing a friend", category: "Relationships", priority: "Build coverage", brief: "Two friends want different things. Show how they explain their feelings, listen, and disagree kindly. Teach the phrases through the story’s resolution.", scope: "A2–B1 audience. Explain the useful language without turning the story into a lecture. No required conjugation set.", forms: [], requirements: teaching, target: 2, reviewedBooks: 0, demoExamples: 0)
        ]
    }
}
