//
// Cuentiva
// Copyright © 2026 3DaysOfSwiftConcurrency.com.
// All rights reserved.
// See LICENSE for permitted use.
//

import SwiftUI

struct ChatIntroductionView: View {
    let locked: Bool
    @Environment(ThemeManager.self) private var theme

    var body: some View {
        VStack(spacing: 16) {
            Text("Today")
                .font(.caption.weight(.semibold))
                .padding(.horizontal, 20).padding(.vertical, 7)
                .background(theme.theme.surface, in: Capsule())
            Text("Messages are generated by AI. Some may be inaccurate or inappropriate.")
                .font(.footnote).multilineTextAlignment(.center)
                .foregroundStyle(theme.theme.muted)
                .padding(.horizontal, 18).padding(.vertical, 14)
                .frame(maxWidth: 340)
                .background(theme.theme.surface, in: RoundedRectangle(cornerRadius: 14))
            if locked {
                Image(systemName: "lock.fill")
                    .font(.system(size: 24, weight: .medium))
                    .foregroundStyle(theme.theme.muted)
                    .padding(.top, 4)
                    .accessibilityLabel("Conversation locked")
            }
        }
        .frame(maxWidth: .infinity)
        .padding(.top, 8).padding(.bottom, 8)
    }
}
